name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # 每天运行一次
  workflow_dispatch:      # 手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 生成贪吃蛇 SVG
        uses: Platane/snk@v3
        with:
          github_user_name: laisc7301
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: 推送 SVG 到 GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
